title: Takato Honda (本田 崇人), Ph.D.
logo: /assets/img/face_2025.png
description: <a href="https://takatohonda.github.io">[English]</a>
             <a href="https://takatohonda.github.io/jp/">[日本語]</a><br>
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: UA-223049185-1